# Generated by Django 3.0.1 on 2020-01-06 08:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('R', 'Red'), ('B', 'Blue'), ('W', 'White'), ('G', 'Green'), ('Gr', 'Gray')], default='R', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'ExtraLarge')], default='M', max_length=10),
        ),
    ]
