# Generated by Django 3.0.1 on 2020-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20200106_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ManyToManyField(to='design.Design'),
        ),
        migrations.AlterField(
            model_name='design',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='design/'),
        ),
    ]
